### ISSUE TITLE
Episodes are not imported(ARM)

### ISSUE THREAD

**Issue by d3545t3r** [SamTV12345/PodFetch#106]
### Describe the bug

There is apparently a problem with the ARM version of podfetch (could only test this) updating episodes.

For tracking:

I completely rebuilt the container and imported my podcasts here (OPML).
All directories in 'podgrab-podcasts' are created and corresponding images are downloaded.

After that the process stops and no episodes are loaded.

Here is the corresponding log:

```
Debug file located at /app/src/target/release/build/podfetch-df2e0023372c1419/out/built.rs
  ____           _ _____    _       _
 |  _ \ ___   __| |  ___|__| |_ ___| |__
 | |_) / _ \ / _` | |_ / _ \ __/ __| '_ \
 |  __/ (_) | (_| |  _|  __/ || (__| | | |
 |_|   \___/ \__,_|_|  \___|\__\___|_| |_|

2023-05-06T08:35:37 [INFO] - No settings found, inserting default settings
2023-05-06T08:35:37 [INFO] - Starting with the following environment variables:
Public server url: http://localhost:86/
Polling interval for new episodes: 60 minutes
GPodder integration enabled: false
Database url is set to: sqlite://./db/podcast.db
Podindex API key&secret configured: false
2023-05-06T08:35:37 [INFO] - starting 4 workers
2023-05-06T08:35:37 [INFO] - Actix runtime found; starting in Actix runtime
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: Empty }', src/service/podcast_episode_service.rs:235:55
stack backtrace:
   0:   0xe8510c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0d267d3ddd434858
   1:   0xeaae70 - core::fmt::write::h7253a9d64981ec1f
   2:   0xe7d218 - std::io::Write::write_fmt::h6d19611cef50d2cb
   3:   0xe86be4 - std::panicking::default_hook::{{closure}}::h7a778041ee0c25b0
   4:   0xe8673c - std::panicking::default_hook::h00d2a169ed3329c4
   5:   0xe873b8 - std::panicking::rust_panic_with_hook::h233948492a2daf92
   6:   0xe870fc - std::panicking::begin_panic_handler::{{closure}}::h0594b0f8e73c9f79
   7:   0xe856dc - std::sys_common::backtrace::__rust_end_short_backtrace::h86679e0e7e726aea
   8:   0xe86eb0 - rust_begin_unwind
   9:   0x4bc94c - core::panicking::panic_fmt::he71af873a4d08fbd
  10:   0x4bca78 - core::result::unwrap_failed::hf16f916d1dba6e7a
  11:   0x58f23c - podfetch::service::podcast_episode_service::PodcastEpisodeService::insert_podcast_episodes::h936e5bd12001a96c
  12:   0x51c47c - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h572df02aa80f45f7
  13:   0x76cca0 - tokio::runtime::task::core::Core<T,S>::poll::h1d708efd78fa42d6
  14:   0x57ebd4 - tokio::runtime::task::harness::Harness<T,S>::poll::h8c994f6f72864cc5
  15:   0xd12a1c - tokio::runtime::blocking::pool::Inner::run::hfface49d139e479e
  16:   0xd0d1b0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h45cd0b36965f8d2e
  17:   0xd0e7dc - core::ops::function::FnOnce::call_once{{vtable.shim}}::hed19b19589300585
  18:   0xe8b03c - std::sys::unix::thread::Thread::new::thread_start::hc48028146cb4213a
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(1616), ...)', src/service/rust_service.rs:169:18
stack backtrace:
   0:   0xe8510c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0d267d3ddd434858
   1:   0xeaae70 - core::fmt::write::h7253a9d64981ec1f
   2:   0xe7d218 - std::io::Write::write_fmt::h6d19611cef50d2cb
   3:   0xe86be4 - std::panicking::default_hook::{{closure}}::h7a778041ee0c25b0
   4:   0xe8673c - std::panicking::default_hook::h00d2a169ed3329c4
   5:   0xe873b8 - std::panicking::rust_panic_with_hook::h233948492a2daf92
   6:   0xe870fc - std::panicking::begin_panic_handler::{{closure}}::h0594b0f8e73c9f79
   7:   0xe856dc - std::sys_common::backtrace::__rust_end_short_backtrace::h86679e0e7e726aea
   8:   0xe86eb0 - rust_begin_unwind
   9:   0x4bc94c - core::panicking::panic_fmt::he71af873a4d08fbd
  10:   0x4bca78 - core::result::unwrap_failed::hf16f916d1dba6e7a
  11:   0x6220a4 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hcecc0745cd91d75e
  12:   0x61b254 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb1b76a062df3f193
  13:   0x51bcc8 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h0ad448ac5ae58cf6
  14:   0x76cf70 - tokio::runtime::task::core::Core<T,S>::poll::h4aadf4118cc0f4b8
  15:   0x57f2fc - tokio::runtime::task::harness::Harness<T,S>::poll::hd90bed8febdc3dce
  16:   0xd12a1c - tokio::runtime::blocking::pool::Inner::run::hfface49d139e479e
  17:   0xd0d1b0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h45cd0b36965f8d2e
  18:   0xd0e7dc - core::ops::function::FnOnce::call_once{{vtable.shim}}::hed19b19589300585
  19:   0xe8b03c - std::sys::unix::thread::Thread::new::thread_start::hc48028146cb4213a
``` 

### Reproduction

start import on a fresh install

### System Info

```Shell
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) arm ARMv7 Processor rev 5 (v7l)
    Memory: 312.07 MB / 999.02 MB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 19.9.0 - /usr/local/bin/node
    npm: 9.6.3 - /usr/local/bin/npm
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Did you solve the problem or are you still experiencing it?
