### ISSUE TITLE
Error When Trying to Look at Podcast During Downloads

### ISSUE THREAD

**Issue by DrMxrcy** [SamTV12345/PodFetch#42]
### Describe the bug

Trying to view a Podcast while downloading 

<img width="1496" alt="CleanShot 2023-04-03 at 22 43 26@2x" src="https://user-images.githubusercontent.com/58747968/229673266-66c5caab-c499-4df2-8723-5e75aaa8149d.png">

```
2023-04-04T04:39:06 [INFO] - Downloading podcast episode: Tesla Opens its Superchargers and Weird MWC Gadgets?
thread 'actix-rt|system:0|arbiter:0' panicked at 'Error acquiring lock: PoisonError { .. }', src/controllers/podcast_controller.rs:44:10
thread 'actix-rt|system:0|arbiter:1' panicked at 'Error locking db: PoisonError { .. }', src/controllers/notification_controller.rs:10:10
thread 'actix-rt|system:0|arbiter:1' panicked at 'Error locking db: PoisonError { .. }', src/controllers/notification_controller.rs:10:10
thread 'actix-rt|system:0|arbiter:1' panicked at 'Error acquiring lock: PoisonError { .. }', src/controllers/podcast_controller.rs:44:10
thread 'actix-rt|system:0|arbiter:0' panicked at 'Error acquiring lock: PoisonError { .. }', src/controllers/podcast_controller.rs:44:10
thread 'actix-rt|system:0|arbiter:1' panicked at 'Error acquiring lock: PoisonError { .. }', src/controllers/podcast_controller.rs:44:10
thread 'actix-rt|system:0|arbiter:0' panicked at 'Error acquiring lock: PoisonError { .. }', src/controllers/podcast_controller.rs:44:10
thread 'actix-rt|system:0|arbiter:0' panicked at 'Error locking db: PoisonError { .. }', src/controllers/notification_controller.rs:10:10
thread 'actix-rt|system:0|arbiter:1' panicked at 'Error locking db: PoisonError { .. }', src/controllers/notification_controller.rs:10:10
thread 'actix-rt|system:0|arbiter:0' panicked at 'Error acquiring lock: PoisonError { .. }', src/controllers/podcast_controller.rs:44:10
thread 'actix-rt|system:0|arbiter:1' panicked at 'Error locking db: PoisonError { .. }', src/controllers/notification_controller.rs:10:10
thread 'actix-rt|system:0|arbiter:0' panicked at 'Error locking db: PoisonError { .. }', src/controllers/notification_controller.rs:10:10
thread 'actix-rt|system:0|arbiter:1' panicked at 'Error locking db: PoisonError { .. }', src/controllers/notification_controller.rs:10:10
thread 'actix-rt|system:0|arbiter:1' panicked at 'Error acquiring lock: PoisonError { .. }', src/controllers/podcast_controller.rs:44:10
thread 'actix-rt|system:0|arbiter:0' panicked at 'Error acquiring lock: PoisonError { .. }', src/controllers/podcast_controller.rs:44:10
thread 'actix-rt|system:0|arbiter:1' panicked at 'Error locking db: PoisonError { .. }', src/controllers/notification_controller.rs:10:10
thread 'actix-rt|system:0|arbiter:1' panicked at 'Error locking db: PoisonError { .. }', src/controllers/notification_controller.rs:10:10
thread 'actix-rt|system:0|arbiter:0' panicked at 'Error acquiring lock: PoisonError { .. }', src/controllers/podcast_controller.rs:44:10
```

### Reproduction

Use the Docker Compose

### System Info

```Shell
Host System

  System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 28.50 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /opt/homebrew/bin/npm

Server
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Thanks for the issue. I guess my thesis that this happens only on really small processors is invalid. Could be an ARM64 issue. Anyways I will refactor the code so that these issues won't appear again.  Due to SQLite downloading podcasts simultaneously is not supported but that doesn't seem to be in your case.

**Comment by SamTV12345** [comment]
Could you try again with the latest image?

**Comment by DrMxrcy** [comment]
Seems to be working now!

**Comment by SamTV12345** [comment]
Awesome. It shouldn't stop the download. So if that happens just do a docker-compose restart. I am working on a MySQL/Postgres integration. That way multiple threads can edit the same table.

**Comment by SamTV12345** [comment]
Fixed. As the next version that will be available on DockerHub in ~6h will have a connection pool and a retry counter if the database is locked.

**Comment by SamTV12345** [comment]
If you like to you can test again on your Mac Pro.
