### ISSUE TITLE
Error When Trying to Look at Podcast During Downloads

### ISSUE THREAD

**Issue by DrMxrcy** [SamTV12345/PodFetch#43]
### Describe the bug

Trying to view a Podcast while downloading 

<img width="1496" alt="CleanShot 2023-04-03 at 22 43 26@2x" src="https://user-images.githubusercontent.com/58747968/229673266-66c5caab-c499-4df2-8723-5e75aaa8149d.png">

```
2023-04-04T04:39:06 [INFO] - Downloading podcast episode: Tesla Opens its Superchargers and Weird MWC Gadgets?
thread 'actix-rt|system:0|arbiter:0' panicked at 'Error acquiring lock: PoisonError { .. }', src/controllers/podcast_controller.rs:44:10
thread 'actix-rt|system:0|arbiter:1' panicked at 'Error locking db: PoisonError { .. }', src/controllers/notification_controller.rs:10:10
thread 'actix-rt|system:0|arbiter:1' panicked at 'Error locking db: PoisonError { .. }', src/controllers/notification_controller.rs:10:10
thread 'actix-rt|system:0|arbiter:1' panicked at 'Error acquiring lock: PoisonError { .. }', src/controllers/podcast_controller.rs:44:10
thread 'actix-rt|system:0|arbiter:0' panicked at 'Error acquiring lock: PoisonError { .. }', src/controllers/podcast_controller.rs:44:10
thread 'actix-rt|system:0|arbiter:1' panicked at 'Error acquiring lock: PoisonError { .. }', src/controllers/podcast_controller.rs:44:10
thread 'actix-rt|system:0|arbiter:0' panicked at 'Error acquiring lock: PoisonError { .. }', src/controllers/podcast_controller.rs:44:10
thread 'actix-rt|system:0|arbiter:0' panicked at 'Error locking db: PoisonError { .. }', src/controllers/notification_controller.rs:10:10
thread 'actix-rt|system:0|arbiter:1' panicked at 'Error locking db: PoisonError { .. }', src/controllers/notification_controller.rs:10:10
thread 'actix-rt|system:0|arbiter:0' panicked at 'Error acquiring lock: PoisonError { .. }', src/controllers/podcast_controller.rs:44:10
thread 'actix-rt|system:0|arbiter:1' panicked at 'Error locking db: PoisonError { .. }', src/controllers/notification_controller.rs:10:10
thread 'actix-rt|system:0|arbiter:0' panicked at 'Error locking db: PoisonError { .. }', src/controllers/notification_controller.rs:10:10
thread 'actix-rt|system:0|arbiter:1' panicked at 'Error locking db: PoisonError { .. }', src/controllers/notification_controller.rs:10:10
thread 'actix-rt|system:0|arbiter:1' panicked at 'Error acquiring lock: PoisonError { .. }', src/controllers/podcast_controller.rs:44:10
thread 'actix-rt|system:0|arbiter:0' panicked at 'Error acquiring lock: PoisonError { .. }', src/controllers/podcast_controller.rs:44:10
thread 'actix-rt|system:0|arbiter:1' panicked at 'Error locking db: PoisonError { .. }', src/controllers/notification_controller.rs:10:10
thread 'actix-rt|system:0|arbiter:1' panicked at 'Error locking db: PoisonError { .. }', src/controllers/notification_controller.rs:10:10
thread 'actix-rt|system:0|arbiter:0' panicked at 'Error acquiring lock: PoisonError { .. }', src/controllers/podcast_controller.rs:44:10
```

### Reproduction

Use the Docker Compose, Put it behind Traefik, Once started add a podcast. Try to view the podcast

### System Info

```Shell
Host System

  System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 28.50 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /opt/homebrew/bin/npm

Server

  System:
    OS: Linux 5.4 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (2) x64 AMD EPYC Processor
    Memory: 12.45 GB / 15.63 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DrMxrcy** [comment]
Duplicate of #42
