### ISSUE TITLE
Error "not admin or uploader" when adding specific podcast "alle bekloppt" via iTunes search

### ISSUE THREAD

**Issue by makuris** [SamTV12345/PodFetch#556]
### Describe the bug

I hope I do not waste anyones time, I was not able to find this topic via searching and I think it is some sort of bug.
Thank you for this great piece of software which is really useful for me.

I set up my Podfetch instance as docker container and added all my podcasts.
Everything is working fine until I added the "alle bekloppt" podcast [](https://feedpress.me/allebekloppt)
I tried to add it via the link as well as via the iTunes search. Both with a fresh installation for testing.
Each time I get the error message "no admin or uploader", then the podcast is briefly visible until it is no longer part of the list.
However, when trying to add it again the error message "already subscribed" is shown.

It is not possible to listen to this podcast, since it is not visible. Does anyone have an idea why this is not working. I guess there must be someting special about this very podcast since others work just fine - so my setup can't be completely wrong.

This is what I found in the logs right after I clicked on the "add podcast" icon. I do not have enough knowledge to understand any of this. I hope this helps to identify the cause.
```
2024-01-18T12:10:36 ℹ️ - Found podcast: https://itunes.apple.com/search?term=&term=alle+bekloppt&entity=podcast
thread 'tokio-runtime-worker' panicked at src/models/podcast_episode.rs:167:63:
Error parsing date: ParseError(Impossible)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'actix-rt|system:0|arbiter:3' panicked at src/service/rust_service.rs:202:18:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(122), ...)
```

### Reproduction

add new podcast - search for "alle bekloppt" in iTunes - click on plus icon

### System Info

```Shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i5-4590T CPU @ 2.00GHz
    Memory: 123.52 MB / 7.65 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 12.22.12 - /usr/bin/node
    npm: 7.5.2 - /usr/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
No you didn't. Thanks for posting your podcast. It is indeed an error in the feed. One podcast episode contained an invalid publication date which caused an error when I tried to parse the string to an object. This should be fixed now and the current date is simply taken if there is an error with the publication date.
