### ISSUE TITLE
panicked when Polling for new episodes

### ISSUE THREAD

**Issue by stelle007** [SamTV12345/PodFetch#615]
### Describe the bug

I am getting different panicked errors like the below, both when Polling for new episodes or refreshing. After I get a panicked, it will not do Pollingnagain, and I have to restart the container.

_thread '<unnamed>' panicked at src/service/podcast_episode_service.rs:121:86:
called `Result::unwrap()` on an `Err` value: Eof
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace_

I have tried removing some podcasts that were the source for this, but it seems random. It do not happen all the time, so if I manually refresh, it might refresh fine.

Is there a way that I can identify what podcasts generate the issue?

I absolute love this Project, just wish I didn't have to manually restart app container five times a day.

Thank you.

### Reproduction

Random, but happens every day when pooling for episodes.

### System Info

```Shell
Docker Container behind nginx reverce proxy.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
I added better debug statements in the latest build. Could you upgrade and see if the error persists and if yes paste the logs?

**Comment by stelle007** [comment]
Thank you.
I have now updated, and will upload the logs for both DB and App container if the error persists.

**Comment by stelle007** [comment]
unfortunately it happened again, Here are my logs:
 
App Log:
| |_) / _ \ / _` | |_ / _ \ __/ __| '_ \
 |  __/ (_) | (_| |  _|  __/ || (__| | | |
 |_|   \___/ \__,_|_|  \___|\__\___|_| |_|
       

2024-02-14T17:03:21 ℹ️ - Settings already present
2024-02-14T17:03:21 ℹ️ - Starting with the following environment variables:
2024-02-14T17:03:21 ℹ️ - Public server url: https://pod.sorskov.dk/
2024-02-14T17:03:21 ℹ️ - Polling interval for new episodes: 60 minutes
2024-02-14T17:03:21 ℹ️ - Developer specifications available at https://pod.sorskov.dk/swagger-ui/index.html#/
2024-02-14T17:03:21 ℹ️ - GPodder integration enabled: true
2024-02-14T17:03:21 ℹ️ - Podindex API key&secret configured: false
2024-02-14T17:03:21 ℹ️ - starting 4 workers
2024-02-14T17:03:21 ℹ️ - Actix runtime found; starting in Actix runtime
2024-02-14T18:00:00 ℹ️ - Polling for new episodes
2024-02-14T18:00:17 ℹ️ - Downloading podcast episode: Onsdag 14. feb. 2024
2024-02-14T19:00:00 ℹ️ - Polling for new episodes
2024-02-14T20:00:00 ℹ️ - Polling for new episodes
2024-02-14T21:00:00 ℹ️ - Polling for new episodes
2024-02-14T22:00:00 ℹ️ - Polling for new episodes
2024-02-14T23:00:00 ℹ️ - Polling for new episodes
2024-02-15T00:00:00 ℹ️ - Polling for new episodes
2024-02-15T01:00:00 ℹ️ - Polling for new episodes
2024-02-15T01:00:23 ℹ️ - Downloading podcast episode: 219. Question Time: Vladimir Putin’s strategy, Labour’s selection headache, and VAT on private schools
2024-02-15T02:00:00 ℹ️ - Polling for new episodes
2024-02-15T03:00:00 ℹ️ - Polling for new episodes
2024-02-15T03:00:06 ℹ️ - Downloading podcast episode: Politiet jagter dansker i sag om lejemord og narko
thread '<unnamed>' panicked at src/service/podcast_episode_service.rs:539:14:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("politiken.dk")), port: None, path: "/webservice/podcast/channels/channel_dulytter/feed/itunes/", query: None, fragment: None }, source: TimedOut }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


Database Log

PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-02-14 07:14:14.163 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-02-14 07:14:14.163 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-02-14 07:14:14.163 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-02-14 07:14:14.184 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-02-14 07:14:14.189 UTC [29] LOG:  database system was shut down at 2024-02-14 07:13:59 UTC
2024-02-14 07:14:14.194 UTC [1] LOG:  database system is ready to accept connections
2024-02-14 07:19:14.288 UTC [27] LOG:  checkpoint starting: time
2024-02-14 07:23:21.902 UTC [27] LOG:  checkpoint complete: wrote 2480 buffers (15.1%); 0 WAL file(s) added, 0 removed, 1 recycled; write=247.510 s, sync=0.048 s, total=247.615 s; sync files=30, longest=0.037 s, average=0.002 s; distance=18445 kB, estimate=18445 kB; lsn=0/70CCB568, redo lsn=0/70CCB008
2024-02-14 08:04:15.755 UTC [27] LOG:  checkpoint starting: time
2024-02-14 08:08:24.530 UTC [27] LOG:  checkpoint complete: wrote 2494 buffers (15.2%); 0 WAL file(s) added, 0 removed, 1 recycled; write=248.702 s, sync=0.029 s, total=248.775 s; sync files=24, longest=0.026 s, average=0.002 s; distance=18641 kB, estimate=18641 kB; lsn=0/71EFF778, redo lsn=0/71EFF740
2024-02-14 09:04:16.680 UTC [27] LOG:  checkpoint starting: time
2024-02-14 09:08:25.977 UTC [27] LOG:  checkpoint complete: wrote 2498 buffers (15.2%); 0 WAL file(s) added, 0 removed, 2 recycled; write=249.208 s, sync=0.030 s, total=249.298 s; sync files=32, longest=0.027 s, average=0.001 s; distance=18580 kB, estimate=18635 kB; lsn=0/731249A0, redo lsn=0/73124968
2024-02-14 10:04:18.128 UTC [27] LOG:  checkpoint starting: time
2024-02-14 10:08:26.655 UTC [27] LOG:  checkpoint complete: wrote 2485 buffers (15.2%); 0 WAL file(s) added, 0 removed, 1 recycled; write=248.503 s, sync=0.004 s, total=248.527 s; sync files=29, longest=0.004 s, average=0.001 s; distance=18420 kB, estimate=18614 kB; lsn=0/74321AF8, redo lsn=0/74321AC0
2024-02-14 11:04:19.803 UTC [27] LOG:  checkpoint starting: time
2024-02-14 11:08:26.853 UTC [27] LOG:  checkpoint complete: wrote 2478 buffers (15.1%); 0 WAL file(s) added, 0 removed, 1 recycled; write=247.006 s, sync=0.031 s, total=247.051 s; sync files=24, longest=0.031 s, average=0.002 s; distance=18663 kB, estimate=18663 kB; lsn=0/7555B8D8, redo lsn=0/7555B8A0
2024-02-14 12:04:20.976 UTC [27] LOG:  checkpoint starting: time
2024-02-14 12:04:36.885 UTC [27] LOG:  checkpoint complete: wrote 159 buffers (1.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=15.827 s, sync=0.044 s, total=15.902 s; sync files=13, longest=0.026 s, average=0.004 s; distance=1016 kB, estimate=16898 kB; lsn=0/756598E0, redo lsn=0/756598A8
2024-02-14 15:44:25.081 UTC [27] LOG:  checkpoint starting: time
2024-02-14 15:44:25.653 UTC [27] LOG:  checkpoint complete: wrote 6 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.502 s, sync=0.033 s, total=0.572 s; sync files=4, longest=0.028 s, average=0.009 s; distance=6 kB, estimate=15209 kB; lsn=0/7565B480, redo lsn=0/7565B448
2024-02-14 16:14:26.253 UTC [27] LOG:  checkpoint starting: time

2024-02-14 16:18:32.727 UTC [27] LOG:  checkpoint complete: wrote 2466 buffers (15.1%); 0 WAL file(s) added, 0 removed, 1 recycled; write=246.401 s, sync=0.030 s, total=246.475 s; sync files=29, longest=0.030 s, average=0.002 s; distance=18520 kB, estimate=18520 kB; lsn=0/76871680, redo lsn=0/76871648
2024-02-14 17:04:27.605 UTC [27] LOG:  checkpoint starting: time

**Comment by SamTV12345** [comment]
Seems like something is wrong with the rss feed. Can you please provide the link to the podcast?

**Comment by stelle007** [comment]
Thank you for looking into this.
The feed  is: https://politiken.dk/webservice/podcast/channels/channel_dulytter/feed/itunes/

I see "source: TimedOut" in the error, and it worked fine next time I polled for episodes. 
Is it possible that you could fix it so that it will not stop "Polling for new episodes", until I restart the container?

Thank you.

**Comment by stelle007** [comment]
Update: 

Today I restarted at 2024-02-19T08:11:59 Polled manually. It Polled automatically and then panicked at 13:00:06, and now do not Polle automatically any longer.

2024-02-19T09:00:00 ℹ️ - Polling for new episodes
2024-02-19T09:00:13 ℹ️ - Downloading podcast episode: Mandag 19. feb. 2024
2024-02-19T10:00:00 ℹ️ - Polling for new episodes
2024-02-19T11:00:00 ℹ️ - Polling for new episodes
2024-02-19T12:00:00 ℹ️ - Polling for new episodes
2024-02-19T13:00:00 ℹ️ - Polling for new episodes
2024-02-19T13:00:06 ℹ️ - Error parsing podcast "" with cause Eof
thread '<unnamed>' panicked at src/main.rs:233:51:
called `Result::unwrap()` on an `Err` value: BadRequest("Error parsing podcast Eof")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by SamTV12345** [comment]
> Update:
> 
> Today I restarted at 2024-02-19T08:11:59 Polled manually. It Polled automatically a few times, then panicked at 13:00:06, and don not polle automatically any longer.
> 
> 2024-02-19T09:00:00 ℹ️ - Polling for new episodes 2024-02-19T09:00:13 ℹ️ - Downloading podcast episode: Mandag 19. feb. 2024 2024-02-19T10:00:00 ℹ️ - Polling for new episodes 2024-02-19T11:00:00 ℹ️ - Polling for new episodes 2024-02-19T12:00:00 ℹ️ - Polling for new episodes 2024-02-19T13:00:00 ℹ️ - Polling for new episodes 2024-02-19T13:00:06 ℹ️ - Error parsing podcast "" with cause Eof thread '' panicked at src/main.rs:233:51: called `Result::unwrap()` on an `Err` value: BadRequest("Error parsing podcast Eof") note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I relaxed the algorithm a bit. Now when an error occurs it will continue with the sync without you needing to restart the application.

**Comment by SamTV12345** [comment]
> > > Update:
> > > Today I restarted at 2024-02-19T08:11:59 Polled manually. It Polled automatically a few times, then panicked at 13:00:06, and don not polle automatically any longer.
> > > 2024-02-19T09:00:00 ℹ️ - Polling for new episodes 2024-02-19T09:00:13 ℹ️ - Downloading podcast episode: Mandag 19. feb. 2024 2024-02-19T10:00:00 ℹ️ - Polling for new episodes 2024-02-19T11:00:00 ℹ️ - Polling for new episodes 2024-02-19T12:00:00 ℹ️ - Polling for new episodes 2024-02-19T13:00:00 ℹ️ - Polling for new episodes 2024-02-19T13:00:06 ℹ️ - Error parsing podcast "" with cause Eof thread '' panicked at src/main.rs:233:51: called `Result::unwrap()` on an `Err` value: BadRequest("Error parsing podcast Eof") note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > 
> > 
> > I relaxed the algorithm a bit. Now when an error occurs it will continue with the sync without you needing to restart the application.
> 
> That sounds great, when do you think it will be up so that I can pull a new image? Thank you.

Should be available at latest.

**Comment by stelle007** [comment]
Now it's working, Thank you !!!

Log now shows this:
2024-02-23T05:00:37.147298526Z 2024-02-23T05:00:37 ℹ️ - Polling for new episodes successful
2024-02-23T06:00:00.517630201Z 2024-02-23T06:00:00 ℹ️ - Polling for new episodes
2024-02-23T06:00:23.906923407Z 2024-02-23T06:00:23 ℹ️ - Error parsing podcast "" with cause Eof
2024-02-23T06:00:23.908792474Z 2024-02-23T06:00:23 ❌ - Error polling for new episodes: Bad Request: Error parsing podcast Eof
2024-02-23T07:00:00.276985953Z 2024-02-23T07:00:00 ℹ️ - Polling for new episodes
2024-02-23T07:00:04.743714425Z 2024-02-23T07:00:04 ℹ️ - Error parsing podcast "" with cause Eof
2024-02-23T07:00:04.745260860Z 2024-02-23T07:00:04 ❌ - Error polling for new episodes: Bad Request: Error parsing podcast Eof
2024-02-23T08:00:00.117844670Z 2024-02-23T08:00:00 ℹ️ - Polling for new episodes
2024-02-23T08:00:07.893052045Z 2024-02-23T08:00:07 ℹ️ - Downloading podcast episode: Back at Base: Episode 3 - A Shot at Redemption
2024-02-23T08:00:38.960142100Z 2024-02-23T08:00:38 ℹ️ - Polling for new episodes successful
2024-02-23T09:00:00.335919427Z 2024-02-23T09:00:00 ℹ️ - Polling for new episodes
2024-02-23T09:00:13.184533504Z 2024-02-23T09:00:13 ℹ️ - Downloading podcast episode: Fredag 23. feb. 2024
2024-02-23T09:00:39.375255389Z 2024-02-23T09:00:39 ℹ️ - Polling for new episodes successful

Is there a way to see what Podcast/Episode is failing?

**Comment by stelle007** [comment]
So it was running great, up to I started letting my phone sync with gpodder enabled, now I get thiese errors, and it stopped refreshing.

2024-02-25T20:31:13.886973395Z thread 'actix-rt|system:0|arbiter:3' panicked at src/models/subscription.rs:136:26:

2024-02-25T20:31:13.886992602Z called `Result::unwrap()` on an `Err` value: DatabaseError(Unknown, "column \"deleted\" is of type timestamp without time zone but expression is of type integer")

2024-02-25T21:00:00.534548680Z 2024-02-25T21:00:00 ℹ️ - Polling for new episodes

2024-02-25T21:00:33.780641679Z 2024-02-25T21:00:33 ℹ️ - Polling for new episodes successful

2024-02-25T22:00:00.153244121Z 2024-02-25T22:00:00 ℹ️ - Polling for new episodes

2024-02-25T22:00:31.373354049Z thread '<unnamed>' panicked at src/service/podcast_episode_service.rs:554:14:

2024-02-25T22:00:31.373397321Z called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("podcasts.files.bbci.co.uk")), port: None, path: "/p07h19zz.rss", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 99, kind: AddrNotAvailable, message: "Address not available" })) }

2024-02-26T02:01:28.358999162Z thread 'actix-rt|system:0|arbiter:2' panicked at src/models/subscription.rs:136:26:

2024-02-26T02:01:28.359016395Z called `Result::unwrap()` on an `Err` value: DatabaseError(Unknown, "column \"deleted\" is of type timestamp without time zone but expression is of type integer")

2024-02-26T07:13:00.450101389Z thread 'actix-rt|system:0|arbiter:1' panicked at src/models/subscription.rs:136:26:

2024-02-26T07:13:00.450117179Z called `Result::unwrap()` on an `Err` value: DatabaseError(Unknown, "column \"deleted\" is of type timestamp without time zone but expression is of type integer")

2024-02-26T07:56:55.961601536Z thread 'actix-rt|system:0|arbiter:3' panicked at src/models/subscription.rs:136:26:

2024-02-26T07:56:55.961620021Z called `Result::unwrap()` on an `Err` value: DatabaseError(Unknown, "column \"deleted\" is of type timestamp without time zone but expression is of type integer")

2024-02-26T08:11:27.053278236Z thread 'actix-rt|system:0|arbiter:3' panicked at src/models/subscription.rs:136:26:

2024-02-26T08:11:27.053296361Z called `Result::unwrap()` on an `Err` value: DatabaseError(Unknown, "column \"deleted\" is of type timestamp without time zone but expression is of type integer")

2024-02-26T08:40:12.005538896Z thread 'actix-rt|system:0|arbiter:2' panicked at src/models/subscription.rs:136:26:

2024-02-26T08:40:12.005556188Z called `Result::unwrap()` on an `Err` value: DatabaseError(Unknown, "column \"deleted\" is of type timestamp without time zone but expression is of type integer")

2024-02-26T09:27:43.547192697Z thread 'actix-rt|system:0|arbiter:2' panicked at src/models/subscription.rs:136:26:

2024-02-26T09:27:43.547212284Z called `Result::unwrap()` on an `Err` value: DatabaseError(Unknown, "column \"deleted\" is of type timestamp without time zone but expression is of type integer")

2024-02-26T10:47:44.001439501Z thread 'actix-rt|system:0|arbiter:3' panicked at src/models/subscription.rs:136:26:

2024-02-26T10:47:44.001453117Z called `Result::unwrap()` on an `Err` value: DatabaseError(Unknown, "column \"deleted\" is of type timestamp without time zone but expression is of type integer")

**Comment by SamTV12345** [comment]
> So it was running great, up to I started letting my phone sync with gpodder enabled, now I get thiese errors, and it stopped refreshing.
> 
> 2024-02-25T20:31:13.886973395Z thread 'actix-rt|system:0|arbiter:3' panicked at src/models/subscription.rs:136:26:
> 
> 2024-02-25T20:31:13.886992602Z called `Result::unwrap()` on an `Err` value: DatabaseError(Unknown, "column "deleted" is of type timestamp without time zone but expression is of type integer")
> 
> 2024-02-25T21:00:00.534548680Z 2024-02-25T21:00:00 ℹ️ - Polling for new episodes
> 
> 2024-02-25T21:00:33.780641679Z 2024-02-25T21:00:33 ℹ️ - Polling for new episodes successful
> 
> 2024-02-25T22:00:00.153244121Z 2024-02-25T22:00:00 ℹ️ - Polling for new episodes
> 
> 2024-02-25T22:00:31.373354049Z thread '' panicked at src/service/podcast_episode_service.rs:554:14:
> 
> 2024-02-25T22:00:31.373397321Z called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("podcasts.files.bbci.co.uk")), port: None, path: "/p07h19zz.rss", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 99, kind: AddrNotAvailable, message: "Address not available" })) }
> 
> 2024-02-26T02:01:28.358999162Z thread 'actix-rt|system:0|arbiter:2' panicked at src/models/subscription.rs:136:26:
> 
> 2024-02-26T02:01:28.359016395Z called `Result::unwrap()` on an `Err` value: DatabaseError(Unknown, "column "deleted" is of type timestamp without time zone but expression is of type integer")
> 
> 2024-02-26T07:13:00.450101389Z thread 'actix-rt|system:0|arbiter:1' panicked at src/models/subscription.rs:136:26:
> 
> 2024-02-26T07:13:00.450117179Z called `Result::unwrap()` on an `Err` value: DatabaseError(Unknown, "column "deleted" is of type timestamp without time zone but expression is of type integer")
> 
> 2024-02-26T07:56:55.961601536Z thread 'actix-rt|system:0|arbiter:3' panicked at src/models/subscription.rs:136:26:
> 
> 2024-02-26T07:56:55.961620021Z called `Result::unwrap()` on an `Err` value: DatabaseError(Unknown, "column "deleted" is of type timestamp without time zone but expression is of type integer")
> 
> 2024-02-26T08:11:27.053278236Z thread 'actix-rt|system:0|arbiter:3' panicked at src/models/subscription.rs:136:26:
> 
> 2024-02-26T08:11:27.053296361Z called `Result::unwrap()` on an `Err` value: DatabaseError(Unknown, "column "deleted" is of type timestamp without time zone but expression is of type integer")
> 
> 2024-02-26T08:40:12.005538896Z thread 'actix-rt|system:0|arbiter:2' panicked at src/models/subscription.rs:136:26:
> 
> 2024-02-26T08:40:12.005556188Z called `Result::unwrap()` on an `Err` value: DatabaseError(Unknown, "column "deleted" is of type timestamp without time zone but expression is of type integer")
> 
> 2024-02-26T09:27:43.547192697Z thread 'actix-rt|system:0|arbiter:2' panicked at src/models/subscription.rs:136:26:
> 
> 2024-02-26T09:27:43.547212284Z called `Result::unwrap()` on an `Err` value: DatabaseError(Unknown, "column "deleted" is of type timestamp without time zone but expression is of type integer")
> 
> 2024-02-26T10:47:44.001439501Z thread 'actix-rt|system:0|arbiter:3' panicked at src/models/subscription.rs:136:26:
> 
> 2024-02-26T10:47:44.001453117Z called `Result::unwrap()` on an `Err` value: DatabaseError(Unknown, "column "deleted" is of type timestamp without time zone but expression is of type integer")

This sounds like this: https://github.com/SamTV12345/PodFetch/issues/524 . Did you do anything manually or is this a brand new instance?

**Comment by SamTV12345** [comment]
> Now it's working, Thank you !!!
> 
> Log now shows this: 2024-02-23T05:00:37.147298526Z 2024-02-23T05:00:37 ℹ️ - Polling for new episodes successful 2024-02-23T06:00:00.517630201Z 2024-02-23T06:00:00 ℹ️ - Polling for new episodes 2024-02-23T06:00:23.906923407Z 2024-02-23T06:00:23 ℹ️ - Error parsing podcast "" with cause Eof 2024-02-23T06:00:23.908792474Z 2024-02-23T06:00:23 ❌ - Error polling for new episodes: Bad Request: Error parsing podcast Eof 2024-02-23T07:00:00.276985953Z 2024-02-23T07:00:00 ℹ️ - Polling for new episodes 2024-02-23T07:00:04.743714425Z 2024-02-23T07:00:04 ℹ️ - Error parsing podcast "" with cause Eof 2024-02-23T07:00:04.745260860Z 2024-02-23T07:00:04 ❌ - Error polling for new episodes: Bad Request: Error parsing podcast Eof 2024-02-23T08:00:00.117844670Z 2024-02-23T08:00:00 ℹ️ - Polling for new episodes 2024-02-23T08:00:07.893052045Z 2024-02-23T08:00:07 ℹ️ - Downloading podcast episode: Back at Base: Episode 3 - A Shot at Redemption 2024-02-23T08:00:38.960142100Z 2024-02-23T08:00:38 ℹ️ - Polling for new episodes successful 2024-02-23T09:00:00.335919427Z 2024-02-23T09:00:00 ℹ️ - Polling for new episodes 2024-02-23T09:00:13.184533504Z 2024-02-23T09:00:13 ℹ️ - Downloading podcast episode: Fredag 23. feb. 2024 2024-02-23T09:00:39.375255389Z 2024-02-23T09:00:39 ℹ️ - Polling for new episodes successful
> 
> Is there a way to see what Podcast/Episode is failing?

I added the title

**Comment by stelle007** [comment]
> > Now it's working, Thank you !!!
> > Log now shows this: 2024-02-23T05:00:37.147298526Z 2024-02-23T05:00:37 ℹ️ - Polling for new episodes successful 2024-02-23T06:00:00.517630201Z 2024-02-23T06:00:00 ℹ️ - Polling for new episodes 2024-02-23T06:00:23.906923407Z 2024-02-23T06:00:23 ℹ️ - Error parsing podcast "" with cause Eof 2024-02-23T06:00:23.908792474Z 2024-02-23T06:00:23 ❌ - Error polling for new episodes: Bad Request: Error parsing podcast Eof 2024-02-23T07:00:00.276985953Z 2024-02-23T07:00:00 ℹ️ - Polling for new episodes 2024-02-23T07:00:04.743714425Z 2024-02-23T07:00:04 ℹ️ - Error parsing podcast "" with cause Eof 2024-02-23T07:00:04.745260860Z 2024-02-23T07:00:04 ❌ - Error polling for new episodes: Bad Request: Error parsing podcast Eof 2024-02-23T08:00:00.117844670Z 2024-02-23T08:00:00 ℹ️ - Polling for new episodes 2024-02-23T08:00:07.893052045Z 2024-02-23T08:00:07 ℹ️ - Downloading podcast episode: Back at Base: Episode 3 - A Shot at Redemption 2024-02-23T08:00:38.960142100Z 2024-02-23T08:00:38 ℹ️ - Polling for new episodes successful 2024-02-23T09:00:00.335919427Z 2024-02-23T09:00:00 ℹ️ - Polling for new episodes 2024-02-23T09:00:13.184533504Z 2024-02-23T09:00:13 ℹ️ - Downloading podcast episode: Fredag 23. feb. 2024 2024-02-23T09:00:39.375255389Z 2024-02-23T09:00:39 ℹ️ - Polling for new episodes successful
> > Is there a way to see what Podcast/Episode is failing?
> 
> I added the title

That is perfect.

I now noised this:
2024-03-04T13:00:00.677573923Z 2024-03-04T13:00:00 ℹ️ - Polling for new episodes
2024-03-04T13:00:04.723122874Z 2024-03-04T13:00:04 ℹ️ - Error parsing podcast Borgen unplugged "" with cause Eof
2024-03-04T13:00:04.724761283Z 2024-03-04T13:00:04 ❌ - Error polling for new episodes: Bad Request: Error parsing podcast Borgen unplugged with cause Eof
2024-03-04T14:00:00.094149944Z 2024-03-04T14:00:00 ℹ️ - Polling for new episodes
2024-03-04T14:00:34.452353765Z 2024-03-04T14:00:34 ℹ️ - Polling for new episodes successful 

And the wired thing is that there is no new episode to download on that podcast, I'll check if this one specifically fails randomly.
Thank you.

**Comment by SamTV12345** [comment]
Any news on this one?
