### ISSUE TITLE
can't import or sync on openwrt

### ISSUE THREAD

**Issue by jenningsloy318** [SamTV12345/PodFetch#938]
### Describe the bug

I compile this application on openwrt, it can start up successfully, but when I tried to import opml seeds, the error occured
I compiled it with rust 1.81.0 with node 18.20.4

```log
there is no reactor running, must be called from the context of a Tokio 1.x runtime
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
```

Makefile 
```
include $(TOPDIR)/rules.mk
PKG_NAME:=podfetch
PKG_VERSION:=4.7.1
PKG_RELEASE:=1

PKG_BUILD_DEPENDS:=rust node postgresql sqlite3
PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)-$(PKG_VERSION)
PKG_INSTALL_DIR=$(PKG_BUILD_DIR)/target
PKG_SOURCE:=v$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=https://github.com/SamTV12345/PodFetch/archive/refs/tags/
PKG_HASH:=9cc859c3c90707d234af4ffc64fbba619a5485fd9002c1619f15aa7ff27cf5ea

PKG_LICENSE:=Apache License 2.0
PKG_LICENSE_FILES:=LICENSE
PKG_MAINTAINER:=Jennings Liu <jenningsloy318@gmail.com>

PKG_INSTALL:=1
PKG_BUILD_FLAGS:=no-mips16

include $(INCLUDE_DIR)/package.mk
include ../../feeds/packages/lang/rust/rust-package.mk

define Package/podfetch
	SECTION:=utils
	CATEGORY:=Utilities
	TITLE:=PodFetch - A podcast caching application
	DEPENDS:=+libstdcpp +libpq +libsqlite3 +node-npm
endef

define Package/podfetch/description
	A sleek and efficient podcast downloader.
endef


define Build/Prepare
	$(call Build/Prepare/Default)
endef


define Build/Compile
	cd $(PKG_BUILD_DIR)/ui && npm install && npm run build-github
	$(call Build/Compile/Cargo)
endef

define Package/podfetch/install
	$(INSTALL_DIR) $(1)/$(CONFIGURE_PREFIX)/bin/
	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/bin/podfetch $(1)/$(CONFIGURE_PREFIX)/bin/podfetch
	$(INSTALL_DIR) $(1)/etc/podfetch/static
	$(CP) $(PKG_BUILD_DIR)/static/* $(1)/etc/podfetch/static
endef

$(eval $(call BuildPackage,podfetch))
```

### Reproduction

1. set up the openwrt environment 2. use the makefile to build, currently it will build, but package is not successful, I just copy the binary to execute it

### System Info

```Shell
System:
    OS: Linux 5.15 ImmortalWrt 23.05.2
    CPU: (4) arm64 Cortex-A53
    Memory: 329.83 MB / 983.02 MB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.20.4 - /usr/bin/node
    npm: 10.7.0 - /usr/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
> ### Describe the bug
> I compile this application on openwrt, it can start up successfully, but when I tried to import opml seeds, the error occured I compiled it with rust 1.81.0 with node 18.20.4
> 
> ```
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> thread '<unnamed>' panicked at /home/jenningsl/development/openwrt/openwrt-sdk-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/dl/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-util-0.1.8/src/client/legacy/connect/dns.rs:122:24:
> there is no reactor running, must be called from the context of a Tokio 1.x runtime
> ```
> 
> Makefile
> 
> ```
> include $(TOPDIR)/rules.mk
> PKG_NAME:=podfetch
> PKG_VERSION:=4.7.1
> PKG_RELEASE:=1
> 
> PKG_BUILD_DEPENDS:=rust node postgresql sqlite3
> PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)-$(PKG_VERSION)
> PKG_INSTALL_DIR=$(PKG_BUILD_DIR)/target
> PKG_SOURCE:=v$(PKG_VERSION).tar.gz
> PKG_SOURCE_URL:=https://github.com/SamTV12345/PodFetch/archive/refs/tags/
> PKG_HASH:=9cc859c3c90707d234af4ffc64fbba619a5485fd9002c1619f15aa7ff27cf5ea
> 
> PKG_LICENSE:=Apache License 2.0
> PKG_LICENSE_FILES:=LICENSE
> PKG_MAINTAINER:=Jennings Liu <jenningsloy318@gmail.com>
> 
> PKG_INSTALL:=1
> PKG_BUILD_FLAGS:=no-mips16
> 
> include $(INCLUDE_DIR)/package.mk
> include ../../feeds/packages/lang/rust/rust-package.mk
> 
> define Package/podfetch
> 	SECTION:=utils
> 	CATEGORY:=Utilities
> 	TITLE:=PodFetch - A podcast caching application
> 	DEPENDS:=+libstdcpp +libpq +libsqlite3 +node-npm
> endef
> 
> define Package/podfetch/description
> 	A sleek and efficient podcast downloader.
> endef
> 
> 
> define Build/Prepare
> 	$(call Build/Prepare/Default)
> endef
> 
> 
> define Build/Compile
> 	cd $(PKG_BUILD_DIR)/ui && npm install && npm run build-github
> 	$(call Build/Compile/Cargo)
> endef
> 
> define Package/podfetch/install
> 	$(INSTALL_DIR) $(1)/$(CONFIGURE_PREFIX)/bin/
> 	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/bin/podfetch $(1)/$(CONFIGURE_PREFIX)/bin/podfetch
> 	$(INSTALL_DIR) $(1)/etc/podfetch/static
> 	$(CP) $(PKG_BUILD_DIR)/static/* $(1)/etc/podfetch/static
> endef
> 
> $(eval $(call BuildPackage,podfetch))
> ```
> 
> ### Reproduction
> 1. set up the openwrt environment 2. use the makefile to build, currently it will build, but package is not successful, I just copy the binary to execute it
> 
> ### System Info
> ```shell
> System:
>     OS: Linux 5.15 ImmortalWrt 23.05.2
>     CPU: (4) arm64 Cortex-A53
>     Memory: 329.83 MB / 983.02 MB
>     Container: Yes
>     Shell: 5.2.15 - /bin/bash
>   Binaries:
>     Node: 18.20.4 - /usr/bin/node
>     npm: 10.7.0 - /usr/bin/npm
> ```
> 
> ### Used Package Manager
> npm
> 
> ### Validations
> * [x]  Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
> * [x]  Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
> * [x]  Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
> * [x]  Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
> * [x]  The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

I'll debug this tomorrow. I guess this is a PodFetch problem as Rust should compile on OpenWRT.

**Comment by jenningsloy318** [comment]
Yes, I compile rust 1.81.0 on openwrt as defult rust in openwrt is 1.73.0, it is really outdated

**Comment by SamTV12345** [comment]
> Yes, I compile rust 1.81.0 on openwrt as defult rust in openwrt is 1.73.0, it is really outdated

Has the recent version fixed your errors?

**Comment by jenningsloy318** [comment]
no，the app occured this error message is compiled with the latest rust, previous rust can't build

**Comment by SamTV12345** [comment]
Do you have an update? Is it working now on openwrt?

**Comment by jenningsloy318** [comment]
no tests recently, i will try this tonight

**Comment by SamTV12345** [comment]
Is there something like a guide on setting up OpenWRT? Would be interesting to test that out.

**Comment by SamTV12345** [comment]
> [@SamTV12345](https://github.com/SamTV12345) i simply follow the openwrt official guide. for instance
> 
> * https://openwrt.org/docs/guide-developer/toolchain/single.package
> * https://openwrt.org/docs/guide-developer/helloworld/chapter1
> 
> i also made the config here, you can reference https://github.com/jenningsloy318/cool-packages/blob/main/podfetch/Makefile
> 
> today I retried again, found that now previous issue is disappeared, but due to the incomplete build of postgresql on openwrt, it is impossible to link again `libpq.a`, so I tried to build with following parameter
> 
> ```
> cargo build  --release  --package podfetch --bin podfetch --features "sqlite"
> ```
> 
> but it still tried to link against `libpq`, **is it** possible **only** link to sqlite if we choose `--features "sqlite"`

This is fixed. I removed openssl and feature guarded postgres and sqlite support. By default the two crates are bundled and generated. With that command: `cargo build --no-default-features --features="sqlite"` you can compile only sqlite. You don't need any dependency and can run pure cargo commands
